framework: jest
preRun:
  command:
    - yarn install
postMerge:
  pattern:
    - "./e2e/__tests__/toMatchInlineSnapshot.test.ts"
preMerge:
  pattern:
    - "./e2e/__tests__/toMatchInlineSnapshot.test.ts"
postRun:
  command:
    - yarn --version
version: 1.0


