---
framework: "jest"
postMerge:
    pattern:
    - "./e2e/__tests__/*.test.ts"
preMerge:
    pattern:
    - "./e2e/__tests__/*.test.ts"
preRun:
    - yarn install
    - yarn run build
postRun:
    - yarn --version
version: 2.0
