framework: jest
tier: large
postMerge: 
  pattern: 
    - "./e2e/__tests__/*.test.ts"
preMerge:
  pattern:
    - "./e2e/__tests__/*.test.ts"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.1
