framework: jest
preRun:
  command:
    - yarn install
postMerge:
  pattern:
    - "./examples/**/*.spec.ts"
preMerge:
  pattern:
    - "./examples/**/*.spec.ts"
postRun:
  command:
    - yarn --version
version: 1.0


